version: "3.8"
services:
    db:
        image: postgres
        restart: always
        container_name: todo_db
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${DB_PORT}
    backend:
        depends_on:
            - db
        build: /backend
        restart: always
        container_name: todo_backend
        ports:
            - ${APP_PORT}:${APP_PORT}
        environment:
            APP_NAME: ${APP_NAME}
            APP_VERSION: ${APP_VERSION}
            APP_DEVELOPER: ${APP_DEVELOPER}
            APP_PORT: ${APP_PORT}
            DATABASE_URL: ${DATABASE_URL}
        command: bash -c "npx prisma migrate dev --name init && npm run start"
    frontend:
        depends_on:
            - db
            - backend
        build: /frontend
        restart: always
        container_name: todo_frontend
        environment:
            REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        command: npm run start
